name: Site Publisher

on:
  push:
    branches: [ "master" ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Generate site
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [3.5.2]
        java: [temurin@8]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java (temurin@8)
        uses: actions/setup-java@v3
        with:
          distribution: jdkfile
          java-version: 17
          jdkFile: ${{ steps.download-java-temurin-8.outputs.jdkFile }}
      - name: Setup SBT
        uses: Jtalk/setup-sbt@v2.0.0
        with:
          version: 1.10.2


      - name: Generate site
        run: sbt '++ ${{ matrix.scala }}' web/fullBuild

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/target/docs/site