package net.bulbyvr
package wobblelab.db


enum DomRecGeneProperty(val displayName: String) derives OrdinalEncoder, OrdinalDecoder {
  case None extends  DomRecGeneProperty("No Effect")
  case MissingFrontLeftLeg extends DomRecGeneProperty("Missing Front Left Leg")
  case MissingFrontRightLeg extends DomRecGeneProperty("Missing Front Right Leg")
  case MissingBackLeftLeg extends  DomRecGeneProperty("Missing Back Left Leg")
  case MissingBackRightLeg extends DomRecGeneProperty("Missing Back Right Leg")
  case VoicePitchHigh extends DomRecGeneProperty("Voice Pitch High")
  case VoicePitchLow extends DomRecGeneProperty("Voice Pitch Low")
  case VoiceHoarse extends DomRecGeneProperty("Voice Hoarse")
  case SmallPupils extends DomRecGeneProperty("Small Pupils")
  case Eyelids extends DomRecGeneProperty("Eyelids")
  case OblongEyes extends DomRecGeneProperty("Oblong Eyes")
  case MultiPupils extends DomRecGeneProperty("Multi Pupils")
  case Teeth extends DomRecGeneProperty("Teeth")
  case VMouth extends DomRecGeneProperty("V-Mouth")
  case OpenMouth extends DomRecGeneProperty("Open Mouth")
  case TiltedEars extends DomRecGeneProperty("Tilted Ears")
  case NubTail extends DomRecGeneProperty("Nub Tail")
  case StiffTail extends DomRecGeneProperty("Stiff Tail")
  case SlightlyCurledTail extends DomRecGeneProperty("Slightly Curled Tail")
  case CurledTail extends DomRecGeneProperty("Curled Tail")
  case NoTail extends DomRecGeneProperty("No Tail")
  case NoPattern extends DomRecGeneProperty("No Pattern")
  case SplotchPattern extends DomRecGeneProperty("Splotch Pattern")
  case StripePattern extends DomRecGeneProperty("Stripe Pattern")
  case RepeatingPattern extends DomRecGeneProperty("Repeating Pattern")
  case LongEyes extends DomRecGeneProperty("Long Eyes")
  case HorizontalEyes extends DomRecGeneProperty("Horizontal Eyes")
  case SpiralEyes extends DomRecGeneProperty("Spiral Eyes")
  case TriangleEyes extends DomRecGeneProperty("Triangle Eyes")
  case MissingPupilEyes extends DomRecGeneProperty("Missing Pupil Eyes")
  case GeometricEyes extends DomRecGeneProperty("Geometric Eyes")
  case DecorativeEyes extends DomRecGeneProperty("Decorative Eyes")
  case LashesEyes extends DomRecGeneProperty("Lashes Eyes")
  case NoWings extends DomRecGeneProperty("No Wings")
  // this is what conservatives want...
  case MissingLeftWing extends DomRecGeneProperty("Missing Left Wing")
  // this is what liberals want...
  case MissingRightWing extends DomRecGeneProperty("Missing Right Wing")
  case WingIssues extends DomRecGeneProperty("Wing Issues")
  case WingFeathers extends DomRecGeneProperty("Wing Feathers")
  // possibly insect wings?
  case AlignmentNeutral extends DomRecGeneProperty("Neutral Wing Alignment")
  // possibly angel wings? (i havent actually gotten these)
  case AlignmentGood extends DomRecGeneProperty("Good Wing Alignment")
  // possibly bat wings?
  case AlignmentEvil extends DomRecGeneProperty("Evil Wing Alignment")
  case FlatTail extends DomRecGeneProperty("Flat Tail")
  case BulbousTail extends DomRecGeneProperty("Bulbous Tail")
  case RepeatedTail extends DomRecGeneProperty("Repeated Tail")
  case ThinTail extends DomRecGeneProperty("Thin Tail")
  case Tail3D extends DomRecGeneProperty("Tail 3D")
  case NoseExtrusion extends DomRecGeneProperty("Nose Extrusion")
  case NoseSquish extends DomRecGeneProperty("Nose Squish")
  case NoseStretch extends DomRecGeneProperty("Nose Stretch")
  case NoseFlat extends DomRecGeneProperty("Nose Flat")
  case NoseRepeated extends DomRecGeneProperty("Nose Repeated")
  case EarFilled extends DomRecGeneProperty("Ear Filled")
  case EarFloppy extends DomRecGeneProperty("Ear Floppy")
  case EarPartialFlop extends DomRecGeneProperty("Ear Partial Flop")
  case EarSharp extends DomRecGeneProperty("Ear Sharp")
  case EarHalved extends DomRecGeneProperty("Ear Halved")
  case EarConic extends DomRecGeneProperty("Ear Conic")
  case MouthCheeks extends DomRecGeneProperty("Mouth Cheeks")
  case MouthMissingTeeth extends DomRecGeneProperty("Mouth Missing Teeth")
  case MouthPointed extends DomRecGeneProperty("Mouth Pointed")
  case MouthNeutral extends DomRecGeneProperty("Mouth Neutral")
  case MouthSmile extends DomRecGeneProperty("Mouth Smile")
  case MouthFrown extends DomRecGeneProperty("Mouth Frown")
  case MouthCutoff extends DomRecGeneProperty("Mouth Cutoff")
  case MouthWiggle extends DomRecGeneProperty("Mouth Wiggle")
  case EarCurlSynced extends DomRecGeneProperty("Ear Curl Synced")
  case HornsTraditional extends DomRecGeneProperty("Traditional Horns")
  case HornsCenter extends DomRecGeneProperty("Center Horns")
  case HornsNone extends DomRecGeneProperty("No Horns")
  case HornsCurled extends DomRecGeneProperty("Curled Horns")
  case HornsNub extends DomRecGeneProperty("Nub Horns")
  case HornsThick extends DomRecGeneProperty("Thick Horns")
  case HornsThin extends DomRecGeneProperty("Thin Horns")
}
