package net.bulbyvr
package wobblelab.db

import io.circe.syntax.*
import io.circe.*
import io.circe.derivation.*

enum GeneticProperty(val displayName: String) {
  case BodyMetallicPlus extends GeneticProperty("Body Metallic Plus")
  case BodyMetallicMinus extends GeneticProperty("Body Metallic Minus")
  case BodyGlossPlus extends GeneticProperty("Body Gloss Plus")
  case BodyGlossMinus extends GeneticProperty("Body Gloss Minus")
  case BodyEmissionColorRPlus extends GeneticProperty("Body Emission Red Plus")
  case BodyEmissionColorRMinus extends GeneticProperty("Body Emission Red Minus")
  case BodyEmissionColorGPlus extends GeneticProperty("Body Emission Green Plus")
  case BodyEmissionColorGMinus extends GeneticProperty("Body Emission Green Minus")
  case BodyEmissionColorBPlus extends GeneticProperty("Body Emission Blue Plus")
  case BodyEmissionColorBMinus extends GeneticProperty("Body Emission Blue Minus")
  case BodyColorRPlus extends GeneticProperty("Body Color Red Plus")
  case BodyColorRMinus extends GeneticProperty("Body Color Red Minus")
  case BodyColorGPlus extends GeneticProperty("Body Color Green Plus")
  case BodyColorGMinus extends GeneticProperty("Body Color Green Minus")
  case BodyColorBPlus extends GeneticProperty("Body Color Blue Plus")
  case BodyColorBMinus extends GeneticProperty("Body Color Blue Minus")
  case LegMetallicPlus extends GeneticProperty("Leg Metallic Plus")
  case LegMetallicMinus extends GeneticProperty("Leg Metallic Minus")
  case LegGlossPlus extends GeneticProperty("Leg Gloss Plus")
  case LegGlossMinus extends GeneticProperty("Leg Gloss Minus")
  case LegEmissionColorRPlus extends GeneticProperty("Leg Emission Red Plus")
  case LegEmissionColorRMinus extends GeneticProperty("Leg Emission Red Minus")
  case LegEmissionColorGPlus extends GeneticProperty("Leg Emission Green Plus")
  case LegEmissionColorGMinus extends GeneticProperty("Leg Emission Green Minus")
  case LegEmissionColorBPlus extends GeneticProperty("Leg Emission Blue Plus")
  case LegEmissionColorBMinus extends GeneticProperty("Leg Emission Blue Minus")
  case LegColorRPlus extends GeneticProperty("Leg Color Red Plus")
  case LegColorRMinus extends GeneticProperty("Leg Color Red Minus")
  case LegColorGPlus extends GeneticProperty("Leg Color Green Plus")
  case LegColorGMinus extends GeneticProperty("Leg Color Green Minus")
  case LegColorBPlus extends GeneticProperty("Leg Color Blue Plus")
  case LegColorBMinus extends GeneticProperty("Leg Color Blue Minus")
  case NoseEarMetallicPlus extends GeneticProperty("Nose/Ear Metallic Plus")
  case NoseEarMetallicMinus extends GeneticProperty("Nose/Ear Metallic Minus")
  case NoseEarGlossPlus extends GeneticProperty("Nose/Ear Gloss Plus")
  case NoseEarGlossMinus extends GeneticProperty("Nose/Ear Gloss Minus")
  case NoseEarEmissionColorRPlus extends GeneticProperty("Nose/Ear Emission Red Plus")
  case NoseEarEmissionColorRMinus extends GeneticProperty("Nose/Ear Emission Red Minus")
  case NoseEarEmissionColorGPlus extends GeneticProperty("Nose/Ear Emission Green Plus")
  case NoseEarEmissionColorGMinus extends GeneticProperty("Nose/Ear Emission Green Minus")
  case NoseEarEmissionColorBPlus extends GeneticProperty("Nose/Ear Emission Blue Plus")
  case NoseEarEmissionColorBMinus extends GeneticProperty("Nose/Ear Emission Blue Minus")
  case NoseEarColorRPlus extends GeneticProperty("Nose/Ear Color Red Plus")
  case NoseEarColorRMinus extends GeneticProperty("Nose/Ear Color Red Minus")
  case NoseEarColorGPlus extends GeneticProperty("Nose/Ear Color Green Plus")
  case NoseEarColorGMinus extends GeneticProperty("Nose/Ear Color Green Minus")
  case NoseEarColorBPlus extends GeneticProperty("Nose/Ear Color Blue Plus")
  case NoseEarColorBMinus extends GeneticProperty("Nose/Ear Color Blue Minus")
  case NoseModAPlus extends GeneticProperty("Nose Size Plus")
  case NoseModAMinus extends GeneticProperty("Nose Size Minus")
  case HornSizePlus extends GeneticProperty("Horn Size Plus")
  case HornSizeMinus extends GeneticProperty("Horn Size Minus")
  case EarModAPlus extends GeneticProperty("Ear Length Plus")
  case EarModAMinus extends GeneticProperty("Ear Length Minus")
  case EarCurlLeft extends GeneticProperty("Ear Curl Left")
  case EarCurlRight extends GeneticProperty("Ear Curl Right")
  case SnoutModAPlus extends GeneticProperty("Snout Rotation Plus")
  case SnoutModAMinus extends GeneticProperty("Snout Rotation Minus")
  case SnoutModBPlus extends GeneticProperty("Snout Length Plus")
  case SnoutModBMinus extends GeneticProperty("Snout Length Minus")
  case SnoutModCPlus extends GeneticProperty("Snout Size Plus")
  case SnoutModCMinus extends GeneticProperty("Snout Size Minus")
  case HeadSizePlus extends GeneticProperty("Head Size Plus")
  case HeadSizeMinus extends GeneticProperty("Head Size Minus")
  case HeadNumber extends GeneticProperty("Head Number")
  case BodyScaleXPlus extends GeneticProperty("Body Length Plus")
  case BodyScaleXMinus extends GeneticProperty("Body Length Minus")
  case BodyScaleZPlus extends GeneticProperty("Body Height Plus")
  case BodyScaleZMinus extends GeneticProperty("Body Height Minus")
  case BodyScaleYPlus extends GeneticProperty("Body Width Plus")
  case BodyScaleYMinus extends GeneticProperty("Body Width Minus")
  case BodyScaleYZPlus extends GeneticProperty("Body Girth Plus")
  case BodyScaleYZMinus extends GeneticProperty("Body Girth Minus")
  case BodyScaleGlobalPlus extends GeneticProperty("Body Size Plus")
  case BodyScaleGlobalMinus extends GeneticProperty("Body Size Minus")
  case TailScalePlus extends GeneticProperty("Tail Size Plus")
  case TailScaleMinus extends GeneticProperty("Tail Size Minus")
  case TailNum extends GeneticProperty("Tail Number")
  case WingSizePlus extends GeneticProperty("Wing Size Plus")
  case WingSizeMinus extends GeneticProperty("Wing Size Minus")
  case WingNumber extends GeneticProperty("Wing Number")
  case LegScaleXZFrontPlus extends GeneticProperty("Front Leg Girth Plus")
  case LegScaleXZFrontMinus extends GeneticProperty("Front Leg Girth Minus")
  case LegScaleXZBackPlus extends GeneticProperty("Back Leg Girth Plus")
  case LegScaleXZBackMinus extends GeneticProperty("Back Leg Girth Minus")
  case LegScaleYFrontTopPlus extends GeneticProperty("Front Top Leg Length Plus")
  case LegScaleYFrontTopMinus extends GeneticProperty("Front Top Leg Length Minus")
  case LegScaleYFrontBotPlus extends GeneticProperty("Front Bottom Leg Length Plus")
  case LegScaleYFrontBotMinus extends GeneticProperty("Front Bottom Leg Length Minus")
  case LegScaleYBackTopPlus extends GeneticProperty("Back Top Leg Length Plus")
  case LegScaleYBackTopMinus extends GeneticProperty("Back Top Leg Length Minus")
  case LegScaleYBackBotPlus extends GeneticProperty("Back Bottom Leg Length Plus")
  case LegScaleYBackBotMinus extends GeneticProperty("Back Bottom Leg Length Minus")
  case StanceWidthFrontPlus extends GeneticProperty("Front Leg Stance Width Plus")
  case StanceWidthFrontMinus extends GeneticProperty("Front Leg Stance Width Minus")
  case StanceWidthBackPlus extends GeneticProperty("Back Leg Stance Width Plus")
  case StanceWidthBackMinus extends GeneticProperty("Back Leg Stance Width Minus")
  case LegPairsFront extends GeneticProperty("Front Leg Number")
  case LegPairsBack extends GeneticProperty("Back Leg Number")
  case PatternColorRPlus extends GeneticProperty("Pattern Color Red Plus")
  case PatternColorRMinus extends GeneticProperty("Pattern Color Red Minus")
  case PatternColorGPlus extends GeneticProperty("Pattern Color Green Plus")
  case PatternColorGMinus extends GeneticProperty("Pattern Color Green Minus")
  case PatternColorBPlus extends GeneticProperty("Pattern Color Blue Plus")
  case PatternColorBMinus extends GeneticProperty("Pattern Color Blue Minus")
  case PatternEmissionColorRPlus extends GeneticProperty("Pattern Emission Red Plus")
  case PatternEmissionColorRMinus extends GeneticProperty("Pattern Emission Red Minus")
  case PatternEmissionColorGPlus extends GeneticProperty("Pattern Emission Green Plus")
  case PatternEmissionColorGMinus extends GeneticProperty("Pattern Emission Green Minus")
  case PatternEmissionColorBPlus extends GeneticProperty("Pattern Emission Blue Plus")
  case PatternEmissionColorBMinus extends GeneticProperty("Pattern Emission Blue Minus")
  case PatternAlpha extends GeneticProperty("Pattern Intensity")
  case PatternMetallicPlus extends GeneticProperty("Pattern Metallic Plus")
  case PatternMetallicMinus extends GeneticProperty("Pattern Metallic Minus")
  case PatternSmoothnessPlus extends GeneticProperty("Pattern Smoothness Plus")
  case PatternSmoothnessMinus extends GeneticProperty("Pattern Smoothness Minus")
  case PatternNum extends GeneticProperty("Pattern Frequency")
  case PatternFlipX extends GeneticProperty("Pattern Horz. Flip")
  case PatternFlipY extends GeneticProperty("Pattern Vert. Flip")
  case PatternInfo extends GeneticProperty("Pattern Variation")
}

given geneticPropertyCodec: Codec[GeneticProperty] = ConfiguredEnumCodec.derived[GeneticProperty](using conf = Configuration.default)